### ISSUE TITLE
`/stats` - emission

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#308]
#### What would you like to be added:

Provide additional statistical data in `/stats` endpoint.

```json
{
  "emission": {
    "total": number,
    "masternode": number,
    "dex": number,
    "community": number,
    "anchor": number,
    "burned": number
  }
}
```

Total to include burned to keep consistency with other stats in the `/stats` endpoint.

/triage accepted
/area module-api
/priority important-soon

**Comment by fuxingloh** [comment]
/assign @siradji 

Do ping @monstrobishi for more details

**Comment by monstrobishi** [comment]
There are two parts to this:
- Emissions reductions after Eunos height (every 2 weeks, see code examples below)
- Split of rewards fields (Also after Eunos height)

The details are described in a high level in the pink paper:
https://github.com/DeFiCh/pinkpaper/tree/main/emission

Note not all emissions from the pink paper are in use (See code examples below for which ones are in use).

You will want to study the code below, for calculating emissions, it's not implemented very well but you should be able to study the logic:

https://github.com/cakedefi/defi-stats-api/blob/master/src/common/Utility.ts#L76

Otherwise take a look at the C++ implementation here:

https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L112

**Comment by siradji** [comment]
> There are two parts to this:
> 
> - Emissions reductions after Eunos height (every 2 weeks, see code examples below)
> 
> - Split of rewards fields (Also after Eunos height)
> 
> 
> 
> The details are described in a high level in the pink paper:
> 
> https://github.com/DeFiCh/pinkpaper/tree/main/emission
> 
> 
> 
> Note not all emissions from the pink paper are in use (See code examples below for which ones are in use).
> 
> 
> 
> You will want to study the code below, for calculating emissions, it's not implemented very well but you should be able to study the logic:
> 
> 
> 
> https://github.com/cakedefi/defi-stats-api/blob/master/src/common/Utility.ts#L76
> 
> 
> 
> Otherwise take a look at the C++ implementation here:
> 
> 
> 
> https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L112

@monstrobishi The link to the emission calculation is broken. Is there another reference? Thank you.
