### ISSUE TITLE
Addresses with Token balance only, should be discovered as active address.

### ISSUE THREAD

**Issue by fullstackninja864** [DeFiCh/whale#575]
#### Why is this needed:
Address which have only token balances (No UTXO) should be considered as active addresses in `discover` method

**Comment by fuxingloh** [comment]
/area whale-api-wallet

I realized you can't do this until we track the address history. By specification, it should track if an "address" activity > 0 rather than balance > 0. We have to wait for address activity indexed first.

**Comment by fuxingloh** [comment]
But it’s a rare occurrence and usage pattern. Should not block upstream. 

Users that activated an address should have a UTXO sent to it or else it is not technically used yet as they didn’t sign a transaction yet. This implementation was feature complete based on Bitcoin design but have to improve and deviate from it due to our unique need.
