### ISSUE TITLE
Basic DEX PoolSwap & CompositeSwap Indexing

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#705]
#### What would you like to be added:

Simplified indexing of PoolSwap and CompositeSwap to track volume and activity. For Volume and APR tracking only hence Add/Remove Pool DfTx is not required.

/triage accepted
/area module-indexer module-database
/priority important-soon

**Comment by fuxingloh** [comment]
Removing https://github.com/DeFiCh/whale/pull/690 to support #705 (this issue)

**Comment by fuxingloh** [comment]
/assign @monstrobishi 

Very simplified indexing methodology for Oracle Data

**Comment by monstrobishi** [comment]
So is the idea here to call the `getpoolpair` RPC every block and store that data in the DB?

- How do we achieve this with the current whale architecture?
- How would this give us volume, is it looking at the delta between reserves?
- Then using the above we calculate commission?

**Comment by monstrobishi** [comment]
@fuxingloh

**Comment by monstrobishi** [comment]
@fuxingloh 

Regarding bucketed aggregation, I think a slightly different approach is warranted here vs oracle price.

For oracle price, since it is a rolling average, the start of a 30 day period (for instance) is still somewhat valid as the average price over a few hours or a day can still represent a meaningful value. However for poolswap volume since it is a sum, and not an average, bucketing over 30 days would mean that 30 day average is only updated once a month.

I assume the expected behavior is a daily update of the 30 day sum of volume. I propose instead that we do a tiered sum, because we are not storing a scalar value, it allows us to perform daily updates of 30 day volume. Allow me to illustrate the two approaches.

## Bucketed Approach

This approach has a particular issue with the 30 day time window (see last line)

```
for every swap tx:
hourBucket += swap (count is not used here because it's a summation not an average)
dayBucket += swap
monthBucket += swap

after 1 hour:
hourBucket = 0 // this is not highly problematic because we can always use n-1 rather than the latest aggregate

after 1 day:
dayBucket = 0 // this is not highly problematic because we can always use n-1

after 1 month:
monthBucket = 0 // this is problematic as n-1 on a 30 day bucket is month old data
```

## Tiered Sum Approach

This I feel is a more suitable approach as we can control the frequency of update for the longest tier (there is no 1 year volume summation)

```
every hour:
hourTier = sum of swaps in the past hour (similar to oracle `mapPriceAggregated`)

every day:
dayTier = sum of all aggregates in hourTier (24 total) 

every day: // because monthBucket is already the longest tier, we can update it daily rather than monthly
monthBucket = sum of all aggregates in dayTier (30 total)
```

**Comment by fuxingloh** [comment]
Yes, this is the problem with Bucketed Approach. With the Bucketed Approach, you won't have access to `t - 1 unit` but rather `t % 1 unit` data.

My assumption with the "Tiered Sum Approach" as you describe would be computing the sum at every hour? Won't it also make sense to just query `t - 1 unit` to get the previous hour or day?

However, I think we should take another approach by using Bucketed with the benefit of aggregating on every `unit` and accessing `t % 1 unit` data.

### The Approach to get `t % 1 unit`:

As is:
```
for every swap tx:
hourBucket += swap
dayBucket += swap
monthBucket += swap
```

To query:
```
Daily: sum(t % hour - 1, t % hour - 2, t % hour - 3 ...)
Monthy: sum(t % day - 1, t % day - 2, t % day - 3, ...)
```

The problem with the above is`[t % hour - 1]` will not be fully aggregated and just contain partial data. But if we include `[t % hour - 24]` it will contain more data. We could take a percent of `- 24` as we are aggregating the recent hour.

**Comment by monstrobishi** [comment]
@fuxingloh 

Ok yep that makes sense the only thing is we don't need the `monthBucket += swap` in your example as that would just be the `Monthy: sum(t % day - 1, t % day - 2, t % day - 3, ...)` query if I'm not wrong

**Comment by monstrobishi** [comment]
Unless we want to display yearly sum then that's fine too
